//  User Actions
export const SET_USER = 'SET_USER'

//  Course Actions
export const CREATE_COURSE = {
  REQUEST: "CREATE_COURSE_REQUEST",
  SUCCESS: "CREATE_COURSE_SUCCESS",
  FAILURE: "CREATE_COURSE_FAILURE"
}
export const FETCH_ALL_COURSES = {
  REQUEST: "FETCH_ALL_COURSES_REQUEST",
  SUCCESS: "FETCH_ALL_COURSES_SUCCESS",
  FAILURE: "FETCH_ALL_COURSES_FAILURE"
}

export const FETCH_COURSE = {
  REQUEST: "FETCH_COURSE_REQUEST",
  SUCCESS: "FETCH_COURSE_SUCCESS",
  FAILURE: "FETCH_COURSE_FAILURE"
}

//  Lecture Actions
// export const CREATE_LECTURE = 'CREATE_LECTURE'
